<center><h3><font color="#b95033"><b>Regolamento ufficiale del Forum Lux in Tenebra*</b></font></h3></center>

	
[p]1.Lux in Tenebra è un gioco di ruolo play by forum basato sul sistema di regole D&D edizione 3.5 . Il nostro scopo è divertirci insieme e giocare in armonia. Cerchiamo quindi di evitare discussioni inutili, comportamenti aggressivi e prevaricazioni di ogni genere. Lux in Tenebra è frutto della fantasia dei suoi fondatori: qualunque riferimento a fatti realmente accaduti è da considerarsi casuale  (vedi articoli 1, 2, 3 e 7 del Regolamento completo.)[/p] 
[p]2. L'utente � direttamente responsabile del comportamento del proprio personaggio (in breve �PG�) e/o del proprio utente registrato ed � tenuto alla riservatezza sia dei suoi dati personali che alla segretezza della sua password. Ciascun utente � tenuto a rispettare le leggi italiane vigenti sulla pirateria informatica. (vedi articoli 4, 5 e 6 del Regolamento completo).[/p]
[p]3. � vietato iscriversi sotto l�identit� di due o pi� utenti, mentre � consentito avere diversi personaggi in diverse avventure, purch� lo stesso pg non sia presente in due avventure contemporaneamente. Nessuna avventura pu� contare pi� di 8 giocatori (vedi articoli 8 e 9 del Regolamento completo).[/p]
[p]4. Master sono i creatori della trama e i giudici degli eventi: il loro criterio per� deve perlomeno basarsi sulle regole D&D edizione 3.5, anche se i Master possono modificare alcune regole ritenute non efficaci a seconda del contesto e delle proprie preferenze. Essendoci diversi stili di gioco il Forum non valorizza n� penalizza alcun modo di giocar Ie: sar� compito del giocatore scegliere il Master che pi� si conf� al proprio gusto personale. I master sono a pieno titolo moderatori all�interno delle loro avventure, e come i moderatori rispondono al regolamento. Condizione necessaria per gli utenti all�iscrizione in un�avventura � avere un�idea di razza, classe e personalit� del personaggio che si vuole interpretare, oltre a un background che non ha limiti di lunghezza. Al giocatore spetta il compito di mantenere sempre ben distinti fantasia e realt�, cercando di non diventare il personaggio che si � creato. (vedi articoli 10, 11, 12 e 13 del Regolamento completo).[/p] 
[p]5. I post di gioco rientrano nelle tre sezioni delle avventure (avventure veloci, standard e su invito) ove non sono ammessi messaggi fuori da questo contesto. I post chiamati OT, ossia Off Topic (termine comune nelle comunit� virtuali basate sul gioco di ruolo, significa fuori tema, quindi si intendono messaggi del giocatore e non del PG), sono ammessi solo nelle apposite sezioni appunto OT e nella sezione Adunanze. E� vietata qualsiasi forma di pubblicit� che non sia stata precedentemente approvata dallo staff di Lux in Tenebra, con la sola eccezione della segnalazione di libri o film che siano fantasy e inseriti nell�apposita sezione del Forum.  E� inoltre vietato offendere pubblicamente o usare un linguaggio troppo colorito o a sfondo sessuale. (vedi gli articoli 14, 15, 16, 17 e 19 del Regolamento completo)[/p] 
[p]6. E� assolutamente vietato rivelare ad altri utenti i propri dati riservati come il proprio indirizzo IP o la propria password. (vedi l'articolo 18 del Regolamento completo)[/p]

<p align="right"><h3><font color="#b95033">Lo Staff di Lux In Tenebra LiT</b></font></h3></p>

<p>*il presente documento � un riassunto del Regolamento Ufficiale, il documento integrale viene reso disponibile al download in tralce al presente.</p>


