<div id="main_noticeboard">
<div id="Notice5"><p class="notice_title_top">Bacheca</div>
<h3 style="text-align:left;">ARGOMENTI FORUM</h3>
<div id="Notice1"><ul class="notice"><li class="notice_title"><!-- ARG_TITLE --></li><li class="content_board"><div><!-- ARG_IMG --><!-- ARG_DESC --></div><br style='clear:both;'/><!-- ARG_LAST --></li></ul></div>
<div id="Notice2"><ul class="notice"><li class="notice_title"><!-- ARG_TITLE --></li><li class="content_board"><div><!-- ARG_IMG --><!-- ARG_DESC --></div><br style='clear:both;'/><!-- ARG_LAST --></li></ul></div>
<div id="Notice3"><ul class="notice"><li class="notice_title"><!-- ARG_TITLE --></li><li class="content_board"><div><!-- ARG_IMG --><!-- ARG_DESC --></div><br style='clear:both;'/><!-- ARG_LAST --></li></ul></div>
<div id="Notice4"><ul class="notice"><li class="notice_title"><!-- ARG_TITLE --></li><li class="content_board"><div><!-- ARG_IMG --><!-- ARG_DESC --></div><br style='clear:both;'/><!-- ARG_LAST --></li></ul></div>
</div>
